apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: k8-app
  namespace: k8-app
  labels:
    app.kubernetes.io/name: k8-app
    app.kubernetes.io/part-of: k8
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: k8-app
                port:
                  number: 80
