apiVersion: v1
kind: Service
metadata:
  name: k8-app
  namespace: k8-app
  labels:
    app.kubernetes.io/name: k8-app
    app.kubernetes.io/part-of: k8
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: k8-app
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
